#!/bin/bash
#------- qsub option -----------
#PBS -q SQUID-H
#PBS --group=jh210024
#PBS -N kfac
#PBS -j o
#PBS -b 1
#PBS -l gpunum_job=8
#PBS -l elapstim_req=48:00:00

module load BaseGPU/2021
source /sqfs/home/z6b038/vir/py3/bin/activate

export WANDB_MODE=offline
export PYTHONPATH=$PYTHONPATH:/sqfs/home/z6b038/asdfghjkl

cd $PBS_O_WORKDIR

torchrun \
 --standalone \
 --nnodes=1 \
 --nproc_per_node=8 \
   train.py \
    --batch-size=256 \
    --val-batch-size=2048 \
    --lr=0.8 \
    --warmup-factor=0.125 \
    --name asdl
